# Generated by Django 3.0.3 on 2021-08-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('PAN_No', models.CharField(max_length=200)),
                ('UAN_No', models.CharField(max_length=200)),
                ('Basic_pay', models.CharField(max_length=200)),
                ('Benefits', models.CharField(max_length=200)),
                ('Taxes', models.IntegerField(max_length=200)),
            ],
        ),
    ]
