# Generated by Django 3.0.3 on 2021-08-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='payslip',
            old_name='Benefits',
            new_name='pan_No',
        ),
        migrations.RenameField(
            model_name='payslip',
            old_name='Basic_pay',
            new_name='uan_No',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='PAN_No',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='Taxes',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='UAN_No',
        ),
        migrations.AddField(
            model_name='payslip',
            name='basic_pay',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='benefits',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='taxes',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
