# Generated by Django 3.0.3 on 2021-08-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0002_auto_20210819_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='Name',
            new_name='name',
        ),
    ]
